version: '3'

services:
  publisher:
    build:
      context: ./publisher
      target: development
    ports:
      - 8080:80
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:8080'
       - JWT_SECRET=$JWT_SECRET
    networks:
      - mercure

  # subscriber:
  #   build:
  #     context: ./subscriber
  #     target: development
  #   ports:
  #     - 8081:80
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: .
  #   networks:
  #     - mercure

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: $JWT_SECRET
      MERCURE_SUBSCRIBER_JWT_KEY: $JWT_SECRET
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - mercure

volumes:
  mercure_data:
  mercure_config:

networks:
  mercure:
    driver: bridge